config/routes.rb
Rails.application.routes.draw do
  get 'page/about_us'

  get 'page/contact'

  resources :masjids do
    resources :timings
  end
  root 'masjids#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/masjid.rb
class Masjid < ApplicationRecord
  has_many :timings, dependent: :destroy

end

app/models/timing.rb
class Timing < ApplicationRecord
  belongs_to :masjid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/masjids_controller.rb
class MasjidsController < ApplicationController
  before_action :set_masjid, only: [:show, :edit, :update, :destroy]

  # GET /masjids
  # GET /masjids.json
  def index
    @masjids = Masjid.all
  end

  # GET /masjids/1
  # GET /masjids/1.json
  def show
  end

  # GET /masjids/new
  def new
    @masjid = Masjid.new
  end

  # GET /masjids/1/edit
  def edit
  end

  # POST /masjids
  # POST /masjids.json
  def create
    @masjid = Masjid.new(masjid_params)

    respond_to do |format|
      if @masjid.save
        format.html { redirect_to @masjid, notice: 'Masjid was successfully created.' }
        format.json { render :show, status: :created, location: @masjid }
      else
        format.html { render :new }
        format.json { render json: @masjid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masjids/1
  # PATCH/PUT /masjids/1.json
  def update
    respond_to do |format|
      if @masjid.update(masjid_params)
        format.html { redirect_to @masjid, notice: 'Masjid was successfully updated.' }
        format.json { render :show, status: :ok, location: @masjid }
      else
        format.html { render :edit }
        format.json { render json: @masjid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masjids/1
  # DELETE /masjids/1.json
  def destroy
    @masjid.destroy
    respond_to do |format|
      format.html { redirect_to masjids_url, notice: 'Masjid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_masjid
      @masjid = Masjid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def masjid_params
      params.require(:masjid).permit(:name, :address)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def about_us
  end

  def contact
  end
end

app/controllers/timings_controller.rb
class TimingsController < ApplicationController

  def new

  end

  def create
    @masjid = Masjid.find(params[:masjid_id])
    @timings = @masjid.timings.create(timing_params)
    redirect_to masjid_path(@masjid)
  end

  def destroy
    @masjid = Masjid.find(params[:masjid_id])
    @timings = @masjid.timings.find(params[:id])
    @timings.destroy

    redirect_to masjid_path(@masjid)
  end

private
  def timing_params
    params.require(:timing).permit(:day, :fajar, :zohar, :asar, :magrib, :isha)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/masjids_helper.rb
module MasjidsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/timings_helper.rb
module TimingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Namaz timings", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><%= link_to "About", page_about_us_path %></li>
          <li><%= link_to "Contach", page_contact_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
    <% end %>
    <% end %>
    <!--  -->
    <div class="container">
      <div class="row">
        <div class="span9"><%= yield %></div>
      </div>
    </div>

    <!--  -->
  </div>
</body>
</html>

app/views/masjids/_form.html.erb
<%= form_for @masjid, :html => { :class => "form-horizontal masjid" } do |f| %>

  <% if @masjid.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@masjid.errors.count, "error") %> prohibited this masjid from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @masjid.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                masjids_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/masjids/edit.html.erb
<%- model_class = Masjid -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/masjids/index.html.erb
<%- model_class = Masjid -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @masjids.each do |masjid| %>
      <tr>
        <td><%= link_to masjid.id, masjid_path(masjid) %></td>
        <td><%= masjid.name %></td>
        <td><%= masjid.address %></td>
        <td><%=l masjid.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      masjid_path(masjid), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_masjid_path(masjid), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      masjid_path(masjid),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_masjid_path,
            :class => 'btn btn-primary' %>

app/views/masjids/new.html.erb
<%- model_class = Masjid -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/masjids/show.html.erb
<%- model_class = Masjid -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @masjid.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @masjid.address %></dd>
</dl>


<%= link_to t('.back', :default => t("helpers.links.back")),
              masjids_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_masjid_path(@masjid), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              masjid_path(@masjid),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<div class="show_timings">
  <%= render "timings/timing", :masjid => @masjid %>
</div>

<div class="add_timings">
  <%= render "timings/form" %>
</div>

app/views/page/about_us.html.erb
<div class="page-header">
  <h1>About Us</h1>
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/page/contact.html.erb
<div class="page-header">
  <h1>Page#contact</h1>
</div>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/timings/_form.html.erb
<%= form_for [@masjid, @masjid.timings.build], :html => { :class => "form-horizontal masjid" } do |f| %>

<div class="form-group row">
  <%= f.label :date %>
  <%= f.date_field :day, :value => Time.now %>
</div>

<div class="form-group row">
  <%= f.label :fajar %>
  <%= f.time_select :fajar %>
</div>

<div class="form-group row">
  <%= f.label :zohar %>
  <%= f.time_select :zohar %>
</div>

<div class="form-group row">
  <%= f.label :asar %>
  <%= f.time_select :asar %>
</div>

<div class="form-group row">
  <%= f.label :magrib %>
  <%= f.time_select :magrib %>
</div>

<div class="form-group row">
  <%= f.label :isha %>
  <%= f.time_select :isha %>
</div>

<div class="form-group row">
  <%= f.submit :class => 'btn btn-primary btn-xs' %>
</div>


<% end %>

app/views/timings/_timing.html.erb
<table class="table table-sm table-inverse">
  <thead>
    <tr>
      <th>date</th>
      <th>fajar time</th>
      <th>zohar time</th>
      <th>asar time</th>
      <th>magrib time</th>
      <th>isha time</th>
    </tr>
  </thead>
  <tbody>
    <% masjid.timings.each do |timing| %>
      <tr>
        <th scope="row"><%= timing.day %></th>
        <td><%= timing.fajar %></td>
        <td><%= timing.zohar %></td>
        <td><%= timing.asar %></td>
        <td><%= timing.magrib %></td>
        <td><%= timing.isha %></td>
        <td><%= link_to 'delete', [timing.masjid, timing],
          method: :delete,
          class: "btn btn-danger btn-sm"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>